### ISSUE TITLE
Fullscreen, picture height cut off

### ISSUE THREAD

**Issue by mstaveley** [GabZach/ArtSaver#9]
With ArtSaverApp in fullscreen mode.
Pictures that are portrait aspect ratio (height greater than width) have the top and bottom cut off because ArtSaverApp fills the width of the screen.  Lots of cut off heads.

The expected behavior is to fill the height of the screen and place black bars on the sides.

When app not in fullscreen mode and window much wider than height, pics seems to be handled correctly.  But if window is not much wider than height, pics height is cut off.  BTW, this also happens with landscape pics, depending on window aspect ratio.

I can see an argument for this behaviour, but would like a preferences button to say "don't cut of height or width".

ArtSaverApp.app v3.2.zip

**Comment by GabZach** [comment]
Thanks a lot for your feedback.
I think i understand what you mean.

Because of the problem you described, I implemented the setting "Avoid black border" , which also has a slide that allows you to adjust how much is getting cut off.
Did you try that?

**Comment by mstaveley** [comment]
I tried [Avoid black borders], it did not fix the problem on either full [less] or full [more].  I'm not sure what less or more mean in this context either.  Does less have less black border or more black border.  I think the confusion arises from the double negative of "Avoid" with "less".

It is also only available with [Zoom in/out] which I don't want.

**Comment by GabZach** [comment]
Right, I need to look into the whole "avoid black" borders functionality again.

It seems to be broken, plus, I am not sure a lot of people really want to adjust this.

I guess, if the aspect ratio of images are very different from the aspect ratio of the window, then I just cut off a little bit of the images, and leave a little bit of black borders on the other two edges.

**Comment by mstaveley** [comment]
I would suggest, that if the aspect ratio of the image is different from the aspect ratio of the window (or screen in full screen mode - yes I know this is the same thing 😀) then don't cut any of the image off, instead expand the larger dimension to the size of the window and fill the top/bottom or sides with a black border.

**Comment by GabZach** [comment]
In general, I agree, but would you still use that strategy, if your window/screen has, say, 4:3 while the image has 2:1 or even 3:1 ? 
(yes there are such photos ;-) .. )

**Comment by mstaveley** [comment]
Yes, I think my suggestion still applies.  Expand the image until one of the dimensions fits the window size in that dimension and fill the other dimension with black pixels.

**Comment by palijn** [comment]
Hi, 
has there been any progress on not cutting heads ? :)
Most pictures I want to display are ratio 1:1 on a Macbook Air M1 screen.
I'll be happy with black borders, however large, if the whole picture is displayed at some point. (Zoom&pan effects are nice, but not mandatory).
Thanks !

**Comment by GabZach** [comment]
I am very sorry, but I didn't find the time yet to work on that. But I realize that it needs to be solved.
There are other bugs, unfortunately, that need solving first. 
But thanks so much for the reminder!
